# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgi3GygWvPllTcb0jjyCB527eV-o-seO
"""

import pandas as pd
baza= {
    "FISH":[ "Nazirov Jasurbek","Ibrohimov Ozodbek","Sultanov Fazliddin","Akbaraliyev Muhammadkarim","Sodiqjonov Dilmurodjon","Yuldashev Muhammad Yusuf","Abduvihidov Yodgorbek","Muhammadzokirov Ziyodjon","Nomozov Mahmudjon","Muhammadov Ozodbek" ],
    "manzili":[ "Fargona tumani","Vodil tumani","Margilon shahar","Akbarobod tumani","Alpomish tumani","Mirzakul tumani","Ahmadyasaviy tumani","Qorakul tumani","Xazratposhsho tumani","Oltin tumani"],
    "yoshi":[  "19","19","20","22","20","25","23","22","25","29"  ],
    "ish joyi":[ "TATUFF","TATU","TATUUF","TATUJf","TATUFF","DXX","FVV","FNQZ","TATUFF","TATUQf" ],
    "jinsi":["erkak","erkak","erkak","erkak","erkak","erkak","erkak","erkak","erkak","erkak"]
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['manzili']=="Vodil tumani"]
print(filtr)

filtr=db[db['yoshi']=="29"]
print(filtr)

filtr=db[db['ish joyi']=="DXX"]
print(filtr)